version: '3.9'

services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: vipera_db
      POSTGRES_USER: vipera_user
      POSTGRES_PASSWORD: vipera_pass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  web:
    build: .
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             gunicorn vipera.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DB_NAME: vipera_db
      DB_USER: vipera_user
      DB_PASSWORD: vipera_pass
      DB_HOST: db
      DB_PORT: 5432
      DEBUG: "True"

volumes:
  pgdata:
